### ISSUE TITLE
Move to secret objects in Drone

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#1880]
We can store secrets in k8s and reference them in the pipeline:

```
---
kind: secret
name: example

get:
  path: example
  name: example
```
