### ISSUE TITLE
Add ability to create dummy interface

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#2186]
We should support something like:

```
network:
  interfaces:
    - name: dummy0
      dummy: true
```
and create the interface accordingly.
