### ISSUE TITLE
Wipe option for additional disks

### ISSUE THREAD

**Issue by freswa** [talos-systems/talos#2213]
## Feature Request
```
machine:
  disks:
    - device: /dev/disk/by-id/scsi-0HC_Volume_5878184
      wipe: true
      partitions:
        - size: 10737383424
          mountpoint: /var/data
```

To wipe the disk before partitioning, formatting and mounting.

```
machine:
  disks:
    - device: /dev/disk/by-id/scsi-0HC_Volume_5878184
      partitions:
        - size: 10737383424
          mountpoint: /var/data
          wipe: true
```
To wipe the partition before formatting and mounting.
