### ISSUE TITLE
Allow to use full disks without explicitly giving the size

### ISSUE THREAD

**Issue by freswa** [talos-systems/talos#2214]
## Feature Request
```
machine:
  disks:
    - device: /dev/disk/by-id/scsi-0HC_Volume_5878184
      partitions:
        - mountpoint: /var/data
          fullDisk: true
```
Given this option should probably lead to `partition.WithMaximumSize(true)` being passed to `pt.Add()` - see manifest.go:164 ff

It results in the partition using the maximum available size.
