### ISSUE TITLE
Bond lacprate is not correct

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#2646]
### Description
```
Hi ,

@Andrew Rynhard As we discussed in yesterdays meet pasting the bond0 Config i used for the LACP rate issue.
     - interface: bond0
       dhcp: false
       bond:
         mode: 802.3ad
         lacprate: fast
         interfaces:
         - eth0
         - eth1
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`] v0.6.0
- Kubernetes version: [`kubectl version --short`]
- Platform:
