### ISSUE TITLE
Allow  --cloud-provider=external to be set

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#3312]
```yaml
cluster:
  externalCloudProvider:
    enabled: true
    manifests:
      - https://[…].yaml
```

If `enabled` is `true`, `manifests` list may be empty. If `enabled` is `false` (default), `manifests` list must be empty.

If enabled, `--cloud-provider=external` flag should be passed to kubelet, kube-apiserver, kube-controller-manager.

Manifests are merged into `extraManifests` on bootstrap.
