### ISSUE TITLE
inline bootstrap manifests

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#3416]
Add an option to the machine configuration like `cluster.inlineManifests` which allows multi-line strings as values, e.g.:

```yaml
cluster:
   inlineManifests:
     - name: foo-manifest
       manifest: | 
         metadata:
              name: foo
```

We need to update manifests controllers to parse the manifests and add them to the global list of manifests.

`name` should be unique across manifests (it will be used to identify resource holding the manifest, to give context to the errors if the manifest doesn't parse).
