### ISSUE TITLE
diskSelector fails to find disk using only size

### ISSUE THREAD

**Issue by TimJones** [talos-systems/talos#3572]
### Description

In my Talos config I have

```yaml
  install:
    diskSelector:
      size: '<= 256GB'
 ```
but when booting the machine, it fails to find a disk with 
```
[talos] task loadConfig (1/1): failed: failed to parse config: deprecated decode: unknown binary operator <= 256GB
```

### Logs
See above.

### Environment

- Talos version: v0.10.0
- Kubernetes version: v1.21.0
- Platform: metal (using Sidero)
