### ISSUE TITLE
config is valid at installation but invalid at runtime when disabling config persistence

### ISSUE THREAD

**Issue by OGKevin** [talos-systems/talos#3676]
## Bug Report
When using the following config:

```yaml
cluster:
  ca:
    crt: <crt>
    key: ""
  controlPlane:
    endpoint: <endpoint>
  network:
    dnsDomain: cluster.local
    podSubnets:
    - 10.244.0.0/16
    serviceSubnets:
    - 10.96.0.0/12
  token: <token>
debug: false
machine:
  install:
    disk: /dev/mmcblk0
  kubelet:
    extraArgs:
      node-ip: 192.168.2.210
      node-labels: metal.sidero.dev/uuid=00c03114-0000-0000-0000-e45f011f4f30
  network:
    interfaces:
    - cidr: 192.168.2.210/24
      interface: wg0
      wireguard:
        peers:
        - allowedIPs:
          - 0.0.0.0/0
          endpoint: 83.84.110.84:51820
          publicKey: <key>
        privateKey: <key>
    - dhcp: true
      interface: eht0
  token: <token>
  type: worker
persist: false
version: v1alpha1
```

The installation of Talos succeeds, however, after rebooting into Talos and the config is re-fetched due to `persist:  false` the config validation fails and the nodes ends up in a boot loop.

However, when I change persist to `True`  and re-install Talos and reboot to Talos, it works as expected.

### Logs
Looking for the error msg in the code, I've found  https://github.com/talos-systems/go-smbios/blob/d3a32bea731a0c2a60ce7f5eae60253300ef27e1/smbios/smbios.go#L60 which is a perfect match. 
`failed to decode structures: unexpected EOF`
  
### Environment
- booting via Sidero
- Talos version: v0.10.3
- Platform: metal rpi_4

### Kernel args

```bash
kernel:
      args:
      - init_on_alloc=1
      - initrd=initramfs.xz
      - ip=dhcp
      - slab_nomerge
      - pti=on
      - talos.board=rpi_4
      - talos.shutdown=poweroff
      - talos.config=http://192.168.1.200:30005/configdata?uuid=
      - talos.platform=metal
```
