### ISSUE TITLE
OVA cannot encrypt state on first run as partition is already XFS formatted

### ISSUE THREAD

**Issue by nberlee** [talos-systems/talos#3759]
## Bug Report
When booting an OVA for the first time with disk encryption configuration for state the boot will fail with:
`task mountStatePartition(1/1): failed: error mounting: failed to encrypt the partition /dev/sda5, because it is not empty`

This is because when mountStatePartition runs, the partition is already formatted as XFS.

### Description
config:
```
    # Machine system disk encryption configuration.
    systemDiskEncryption:
        # State partition encryption.
        state:
            provider: luks2 # Encryption provider to use for the encryption.
            # Defines the encryption keys generation and storage method.
            keys:
                - # Deterministically generated key from the node UUID and PartitionLabel.
                  nodeID: {}
                  slot: 0 # Key slot number for luks2 encryption.
```
### How to replicate
* Deploy an ova without turning it on (also set the config above in the base64 in `guestinfo.talos.config`
* Mount an arch (or a live distro) and make sure you boot from it the first time
* Verify that `/dev/sda5` is an empty partition
* reboot into Talos
* See that it fails with `task mountStatePartition(1/1): failed: error mounting: failed to encrypt the partition /dev/sda5, because it is not empty`
* reboot again in arch (or a live distro) and see that /dev/sda5 is now actually formatted as XFS

### Environment

- Talos version: [0.10.3]
- Platform: amd64
