### ISSUE TITLE
Make bind-addr 127.0.0.1 the default for controller-manager and scheduler

### ISSUE THREAD

**Issue by nberlee** [talos-systems/talos#3765]
## Feature Request
Do not bind the Controller Manager & Scheduler to non-loopback insecure addresses.

### Description
The flag `--bind-address` is not set to 127.0.0.1 in the kube-scheduler and kube-controller-manager  which makes kube-controller listen to 10252/TCP and scheduler listen to 10251/TCP for metrics purposes. If not set, the default bind-address is 0.0.0.0

Exposing this should only be considered when running for example `kube-prometheus`. In any other case (default) talos should  reduce attack surface by setting the bind address to 127.0.0.1 just like kubeadm does.

**Comment by Ulrar** [comment]
Hi,

For people using kube-prometheus, is there a way to re-expose this currently ? I don't see any mentions of this in the doc, apologies if I missed it.
Thank you

**Comment by okaufmann** [comment]
Just if someone gets here not getting metrics for the controllerManager and the scheudler and didn't find out how to change `bind-addr` to `0.0.0.0`:

You need to set `bind-addr` in your controlplane.yaml as extraArgs for both `controllerManager` and `scheduler` . Here is how I got it finally working:

```yaml
cluster:
  ...
  controllerManager:
      image: ...
      extraArgs:
        bind-address: "0.0.0.0"
  proxy: 
      ...
  scheduler:
      image: ...
      extraArgs:
        bind-address: "0.0.0.0"
```
