### ISSUE TITLE
Simplify trustd configuration

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#409]
We should collapse the username and password combination into a "token":

```
services:
  ...
  trustd:
    token: '<token>'
```
