### ISSUE TITLE
machine configuration changes

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4131]
## Feature Request

Proposed config structure (to be discussed):

```yaml
machine:
  network:
    kubespan:
	   enabled: true # requires cluster.discover.enabled
cluster:
	discovery:
		enabled: true
		registries:
			kubernetes:
			  disabled: false
			discoveryService:
			  disabled: false
			  endpoint: https://discovery.talos.dev/
```
