### ISSUE TITLE
capture the first NIC MAC address

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4132]
## Feature Request

Most probably in `LinkStatusController`, create additional resource which capture the first physical link MAC address:

```yaml
metadata:
  type: MACAddresses.network.talos.dev
  id: first
spec:
  address: 01:02:03:...
```
