### ISSUE TITLE
kubespan: node identify

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4137]
## Feature Request

Provision random node identity (ID) which should be stored in `STATE` partition (generate when missing).

### Description

Proposed resource structure:

```yaml
metadata:
   type: Identities.cluster.talos.dev
   id: local
spec:
   nodeID: <> # stored in the STATE, random
```

Node ID itself can be random bytes + base64 or UUID, or [xxid](https://github.com/jxskiss/xxid)
