### ISSUE TITLE
kubespan identity

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4138]
## Feature Request

When KubeSpan is enabled, node should provision its own KubeSpan identity (mostly Wireguard key) and store that in the `STATE` partition.

### Description

Proposed resource structure:

```yaml
metadata:
  type: KubepsanIdentities.kubespan.talos.dev
  id: local
spec:
  publicKey: 
  privateKey:
  address: # ULA address assigned to the node
```
