### ISSUE TITLE
kubespan: local `Affiliate`

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4139]
## Feature Request

Build local node `Affiliate` pulling information from multiple sources.

### Description

```yaml
metadata:
  type: Affiliates.cluster.talos.dev
  id: <nodeID>
spec:
  addresses: [ , , ]
  hostname:
  nodename: 
  kubespan: #optional
  	 publicKey: 
         address:
         additionalAddresses: [ , , ] # contains "addresses" + things like pod CIDRs
         endpoints: [ , , ]
```
