### ISSUE TITLE
Yaml decode?

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#4192]
## Bug Report

Is it yaml decode bag?

```yaml
cluster:
  controlPlane:
    endpoint: https://172.16.0.10:6443
  clusterName: talos-k8s-hezner
  network:
    dnsDomain: cluster.local
    podSubnets: [10.32.0.0/12,fd00:10:32::/102]
    serviceSubnets: [10.200.0.0/22,fd40:10:200::/112]
```

Talos API does not response 

### Logs

```shell
netaddr.ParseIPPrefix("10.32.0.0/12,fd00:10:32::/102"): ParseIP("10.32.0.0/12,fd00:10:32::"): unexpected character (at "/12,fd00:10:32::")
```

### Environment

On worker node (master has diffèrent version and works fine)
- Talos version: master (v0.12.0-alpha.1-46-gc7e8c4222)
