### ISSUE TITLE
Make possible to disable default Kubernetes controlplane podStatic

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#4560]
## Feature Request

I'd like to disable kube-scheduler and kube-controller-manager on the node (im not sure about kube-api). 
It helps me to run instance from backup and check all statuses or make same changes.
After that run kube-scheduler/kube-controller-manager.

Also it helps me to use small instance as third etcd node for quorum.

my PR #4553 

here my proposal of machineconfig params:

```yaml
machine:
  kubelet:
    staticPod:
      controllerManager:
        disable: true
      scheduler:
        disable: false (default value)
```

In future we can add custom podstatic to here ```machine.kubelet.staticPod.$StaticPodName```

**Comment by sergelogvinov** [comment]
V2 from https://github.com/talos-systems/talos/pull/4553#issuecomment-973139427

```yaml
machine:
  controlplane:
    controllerManager:
       disable: true
    scheduler:
       disable: false (default value)
```
