### ISSUE TITLE
Network Vlan custom mtu size

### ISSUE THREAD

**Issue by sergelogvinov** [talos-systems/talos#4592]
## Feature Request

```yaml
machine:
  network:
    interfaces:
      - interface: eth0
        dhcp: true
        vlans:
          - vlanId: 4003
            mtu: 1400
        mtu: 1500
```

### Description

Some times vlan has different mtu size. Its depend on implementation.
So, it will be better to have this option.
