### ISSUE TITLE
Problems to edit config files

### ISSUE THREAD

**Issue by uhlhosting** [talos-systems/talos#4599]
## Bug Report
Config files are not always editable
### Description
Node Dmesg
```user: warning: [2021-11-26T15:06:23.120709182Z]: [talos] apply config request: immediate false, on reboot false```

Local terminal
```
cosmic@Revenger ~/.talos % talosctl -n 172.18.100.59 edit machineconfig
cosmic@Revenger ~/.talos % talosctl -n 172.18.100.68 edit machineconfig
cosmic@Revenger ~/.talos % talosctl -n 172.18.100.67 edit machineconfig
Apply was skipped: no changes detected.
cosmic@Revenger ~/.talos % talosctl -n 172.18.100.68 edit machineconfig
Apply was skipped: no changes detected.
cosmic@Revenger ~/.talos % talosctl -n 172.18.100.59 edit machineconfig
Apply was skipped: no changes detected.
cosmic@Revenger ~/.talos % 
```

### Logs
Reply after :wq applied on above runned commands.
```
# Editing MachineConfigs.config.talos.dev/v1alpha1 at node 172.18.100.67
#
# 1 error occurred:
#       * 172.18.100.67: rpc error: code = Unknown desc = failed to parse config: decode error: yaml: line 6: did not find expected key
#
#

# Editing MachineConfigs.config.talos.dev/v1alpha1 at node 172.18.100.59
#
# 1 error occurred:
#       * 172.18.100.59: rpc error: code = Unknown desc = failed to parse config: unknown keys found during decoding:

# Editing MachineConfigs.config.talos.dev/v1alpha1 at node 172.18.100.68
#
# 1 error occurred:
#       * 172.18.100.68: rpc error: code = Unknown desc = failed to parse config: unknown keys found during decoding:
```
### Environment

- Talos version: v0.13.3
- Kubernetes version: Client Version: v1.22.4
Server Version: v1.22.3
- Platform: Proxmox

**Comment by smira** [comment]
I'm not sure what the issue is here? Talos doesn't accept invalid machine configuration, but what is specifically wrong?

**Comment by uhlhosting** [comment]
@smira I have followed the video to add PVC storage support,

and I wanted to add the following to the config:
```
    # The `extraArgs` field is used to provide additional flags to the kubelet.
    extraArgs:
       node-labels: openebs.io/engine=mayastor

    # The `extraMounts` field is used to add additional mounts to the kubelet container.
    extraMounts:
        - destination: /var/local
          type: bind
          source: /var/local
          options:
            - rbind
            - rshared
            - rw
           ```

I am not sure where the issues are, or how to know what is wrong in the config when its not shown.
