### ISSUE TITLE
running arbitrary user containers

### ISSUE THREAD

**Issue by smira** [talos-systems/talos#4694]
First iteration: support only containers with read-only root filesystem which already resides on the rootfs: `/usr/local/lib/containers/<name>/`. Container configuration should be in the `/usr/local/etc/containers/<name>.yaml`. 

Such service can be either injected by producing a custom build of Talos or by using system extensions.

Spec:

```yaml
name: foo
container:
  entrypoint: ./foo 
  # rootfs derived automatically from `name`: /lib/containers/foo
  args:
     - blah
     - blah
  mounts:
     - # embed here oci.Mount
depends:
   - service: cri
   - file: /run/machined/machined.sock
   - network:
       - address
       - connectivity
       - hostname
       - etcfiles
restart: never|always
```

As a demo system extension we can do a simple Go "Hello world" webserver.

We need also docs on how to use this feature.

Defaults which are not configurable:

* UID/GID: 0/0
* sharing only network namespace with the host
* OOM score - higher than Talos core services, but lower than CRI pods
* seccomp profile - enabled by default
* Linux capabilities - `*` (don't drop any)
