### ISSUE TITLE
Easy way to specify static pods in the machine configuration

### ISSUE THREAD

**Issue by andrewrynhard** [talos-systems/talos#4727]
### Description

Right now it is ugly/confusing adding static pods using `.machine.files`. A first class way to specify them would improve the UX for this use case.

**Comment by smira** [comment]
Machine configuration:

```yaml
machine:
   pods:
      - apiVersion: v1
        kind: Pod
        metadata:
           name: mypod
           namespace: default
        spec:
```
