### ISSUE TITLE
empty subPath mount propagation

### ISSUE THREAD

**Issue by BobyMCbobs** [talos-systems/talos#4923]
### Description
subPath mounts with PVCs don't appear to propagate.

### Example
The following example is a PVC mounted into a Pod, first as a regular mount and separately as a subPath.
An init container creates a file called in a folder many directories down in the volume.
local-path-provisioner is used as the StorageClass.

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: many-subpath
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local-path
---
apiVersion: v1
kind: Pod
metadata:
  name: many-subpath
spec:
  initContainers:
    - name: create-dirs
      image: alpine:3.15
      command:
        - sh
        - -c
        - |
          mkdir -p /var/lib/postgresql/relocated/14.1/usr/lib/postgresql/14.1/bin
          echo test > /var/lib/postgresql/relocated/14.1/usr/lib/postgresql/14.1/bin/a
      volumeMounts:
        - name: many-subpath
          mountPath: /var/lib/postgresql
  containers:
    - name: shell
      image: alpine:3.15
      command:
        - sleep
        - infinity
      volumeMounts:
        - name: many-subpath
          mountPath: /var/lib/postgresql
        - name: many-subpath
          mountPath: /usr/lib/postgresql/14.1/bin
          subPath: relocated/14.1/usr/lib/postgresql/14.1/bin
  volumes:
    - name: many-subpath
      persistentVolumeClaim:
        claimName: many-subpath
```

The output of the follow command is meant to be `a` but instead is empty.
```
kubectl exec -it -c shell many-subpath -- ls /usr/lib/postgresql/14.1/bin
```

on Minikube, the same manifest and command outputs `a` as expected

### Environment

- Talos version:
```
Server:
	NODE:        192.168.1.6
	Tag:         v0.14.0
	SHA:         675dee0e
	Built:       
	Go version:  go1.17.5
	OS/Arch:     linux/arm64
	Enabled:     RBAC
```
- Kubernetes version: `Server Version: v1.23.1`
- Platform: Metal (Raspberry Pis)

**Comment by smira** [comment]
I would assume https://github.com/rancher/local-path-provisioner is being used here

**Comment by smira** [comment]
```
$ kubectl exec -it -c shell many-subpath -- ls /usr/lib/postgresql/14.1/bin     Пн 07 фев 2022 17:27:38
a
```

the fix is to add a mount to the kubelet so it could see the paths created by local-path-provisioner:

```yaml
machine:
    # Used to provide additional options to the kubelet.
    kubelet: 
     extraMounts:
         - destination: /opt/local-path-provisioner
           type: bind
           source: /opt/local-path-provisioner
           options:
             - bind
             - rshared
             - rw
```

But as `/opt` is overlayfs on Talos, I would even recommend reconfiguring `local-path-provisioner` to use something like `/var/local-path-provisioner` for the root directory and mounting that up in the kubelet.
